#!/bin/sh
#-----------------------------------------------------------------------------------------------
#   Copyright 2019 Pivotal Software
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#----------------------------------------------------------------------------------------------
# Author: Sridhar Paladugu 
# Email: spaladugu@pivotal.io
# Description: install the RTS4MADlib client tool and setup the environment variables

echo "setting up path ....................."

. env.sh

if [ -f ~/.bash_profile ]
then
   echo "export # ********** RTS4MADLIB ************" >> ~/.bashrc
   echo "export RTSMADLIB_HOME=`pwd`" >> ~/.bash_profile
   echo "export RTSMADLIB_DOCKER_REG=$DOCKER_REPO" >> ~/.bash_profile
   echo "export RTSMADLIB_IMG_TAG=$IMG_TAG" >> ~/.bash_profile
   echo 'export PATH=$PATH:$RTSMADLIB_HOME/bin' >> ~/.bash_profile
   echo "export # *********************************" >> ~/.bashrc
   source ~/.bash_profile
elif [-f ~/.bashrc ]
then
   echo "export # ********** RTS4MADLIB ************" >> ~/.bashrc
   echo "export RTSMADLIB_HOME=`pwd`" >> ~/.bashrc
   echo "export RTSMADLIB_DOCKER_REG=$DOCKER_REPO" >> ~/.bashrc
   echo "export RTSMADLIB_IMG_TAG=$IMG_TAG" >> ~/.bash_profile
   echo 'export PATH=$PATH:$RTSMADLIB_HOME/bin' >> ~/.bashrc
   echo "export # *********************************" >> ~/.bashrc
   source ~/.bashrc
fi

echo "RTSMADLIB_HOME=$RTSMADLIB_HOME"
echo "RTSMADLIB_DOCKER_REG=$RTSMADLIB_DOCKER_REG"
echo "RTSMADLIB_IMG_TAG=$RTSMADLIB_IMG_TAG"
echo "Finished installing RTSMADlibClient!"
